[workspace]
resolver = "3"
members = ["tinyserver"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Phrolova <me@phrolova.moe>"]
repository = "https://github.com/PhrolovaMoe/tinystream"
homepage = "https://github.com/PhrolovaMoe/tinystream"
license-file = "./LICENSE"

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"

[workspace.dependencies]
axum = "0.8.9"
dirs = "6.0.0"
notify = "8.2.0"
reqwest = "0.13.4"
serde = { version = "1.0.229", features = ["derive"] }
sqlx = { version = "0.9.0", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "signal", "sync"] }
toml = "1.1.4"
walkdir = "2.5.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
